### ISSUE TITLE
Error when running essentialityTestPair.cpp

### ISSUE THREAD

**Issue by jontlei** [jooslee/ISLE#2]
Ran into a few issues when running essentialityTestPair.cpp:

`Line 32: unused variable 'ranksumy'`
`Line 49: comparison of integer expressions of different signedness: 'unsigned int' and 'int'`
`Line 98: this 'if' clause does not guard...`
`Line 155: this 'if clause does not guard...`
`Line 191: unused variable 'xx'`

**Comment by jooslee** [comment]
Hi, sorry for my late response. did not know that you have asked this question... 
We did not come across this error... you may want to make sure that you run the following commands for parallelization and R-vs-C interface. 

Sys.setenv("PKG_CXXFLAGS"="-fopenmp")
Sys.setenv("PKG_LIBS"="-fopenmp")

library(Rcpp)
library(RcppArmadillo)
library(parallel)
